name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Modules
        run: yarn install
      - name: Run Build
        run: yarn run build
      - name: Run Tests
        run: yarn test
